name: preguntas-abiertas-mcp
data:
  - name: nombre
    required: true
    type: text
  - name: email
    required: true
    type: email
  - name: pregunta1
    required: true
    type: textarea
  - name: pregunta2
    required: true
    type: textarea
  - name: pregunta3
    required: true
    type: textarea
  - name: pregunta4
    required: true
    type: textarea